services:
  tor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relay
    environment:
      - RELAY_TYPE=relay # Adjust to 'bridge' or 'exit' if you want to run at another operating mode
      - TOR_ORPort=9001
      - TOR_DirPort=9030
      - TOR_Nickname=YourTorNickname # Adjust to individual nickname
      - TOR_RelayBandwidthRate=5000 KBytes # Adjust to your bandwith
      - TOR_RelayBandwidthBurst=10000 KBytes # Adjust to your bandwith
      - TZ=Europe/Berlin # Adjust to your timezone
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tor/data:/data:Z
    ports:
      - "9001:9001" 
      - "9030:9030"
    restart: always